name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name eprsystemformekedoina eprsystemformekedoina-erp_backend