name: CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine

    services:
      registry:
        image: edlawitg/code_avengers:erp-backend
        ports:
          - 8000:8001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Docker Compose
        run: |
          # Install Docker Compose using wget
          wget -O docker-compose "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)"
          chmod +x docker-compose

      - name: Build docker
        run: |
          echo ---Building and starting up docker---
          docker-compose up -f "docker-compose.yml" up -d --build
          echo ---Containers up---

      # - name: Run the Container
      #   id: run
      #   run: |
      #     docker run
      # - name: Run Docker container
      #   run: docker run -d -p 8000:8000 --name eprsystemformekedoina eprsystemformekedoina-erp_backend:latest
